// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/barang/barang.proto

package barang

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBarangRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CategoryId    int32                  `protobuf:"varint,2,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBarangRequest) Reset() {
	*x = CreateBarangRequest{}
	mi := &file_proto_barang_barang_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBarangRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBarangRequest) ProtoMessage() {}

func (x *CreateBarangRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_barang_barang_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBarangRequest.ProtoReflect.Descriptor instead.
func (*CreateBarangRequest) Descriptor() ([]byte, []int) {
	return file_proto_barang_barang_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBarangRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBarangRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type GetBarangsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBarangsRequest) Reset() {
	*x = GetBarangsRequest{}
	mi := &file_proto_barang_barang_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBarangsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBarangsRequest) ProtoMessage() {}

func (x *GetBarangsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_barang_barang_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBarangsRequest.ProtoReflect.Descriptor instead.
func (*GetBarangsRequest) Descriptor() ([]byte, []int) {
	return file_proto_barang_barang_proto_rawDescGZIP(), []int{1}
}

type GetBarangRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBarangRequest) Reset() {
	*x = GetBarangRequest{}
	mi := &file_proto_barang_barang_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBarangRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBarangRequest) ProtoMessage() {}

func (x *GetBarangRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_barang_barang_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBarangRequest.ProtoReflect.Descriptor instead.
func (*GetBarangRequest) Descriptor() ([]byte, []int) {
	return file_proto_barang_barang_proto_rawDescGZIP(), []int{2}
}

func (x *GetBarangRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateBarangRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CategoryId    int32                  `protobuf:"varint,3,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBarangRequest) Reset() {
	*x = UpdateBarangRequest{}
	mi := &file_proto_barang_barang_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBarangRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBarangRequest) ProtoMessage() {}

func (x *UpdateBarangRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_barang_barang_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBarangRequest.ProtoReflect.Descriptor instead.
func (*UpdateBarangRequest) Descriptor() ([]byte, []int) {
	return file_proto_barang_barang_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateBarangRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBarangRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateBarangRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type DeleteBarangRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBarangRequest) Reset() {
	*x = DeleteBarangRequest{}
	mi := &file_proto_barang_barang_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBarangRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBarangRequest) ProtoMessage() {}

func (x *DeleteBarangRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_barang_barang_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBarangRequest.ProtoReflect.Descriptor instead.
func (*DeleteBarangRequest) Descriptor() ([]byte, []int) {
	return file_proto_barang_barang_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteBarangRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BarangResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      *CategoryResponse      `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BarangResponse) Reset() {
	*x = BarangResponse{}
	mi := &file_proto_barang_barang_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarangResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarangResponse) ProtoMessage() {}

func (x *BarangResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_barang_barang_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarangResponse.ProtoReflect.Descriptor instead.
func (*BarangResponse) Descriptor() ([]byte, []int) {
	return file_proto_barang_barang_proto_rawDescGZIP(), []int{5}
}

func (x *BarangResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BarangResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BarangResponse) GetCategory() *CategoryResponse {
	if x != nil {
		return x.Category
	}
	return nil
}

type GetBarangsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Barangs       []*BarangResponse      `protobuf:"bytes,1,rep,name=barangs,proto3" json:"barangs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBarangsResponse) Reset() {
	*x = GetBarangsResponse{}
	mi := &file_proto_barang_barang_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBarangsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBarangsResponse) ProtoMessage() {}

func (x *GetBarangsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_barang_barang_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBarangsResponse.ProtoReflect.Descriptor instead.
func (*GetBarangsResponse) Descriptor() ([]byte, []int) {
	return file_proto_barang_barang_proto_rawDescGZIP(), []int{6}
}

func (x *GetBarangsResponse) GetBarangs() []*BarangResponse {
	if x != nil {
		return x.Barangs
	}
	return nil
}

type DeleteBarangResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBarangResponse) Reset() {
	*x = DeleteBarangResponse{}
	mi := &file_proto_barang_barang_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBarangResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBarangResponse) ProtoMessage() {}

func (x *DeleteBarangResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_barang_barang_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBarangResponse.ProtoReflect.Descriptor instead.
func (*DeleteBarangResponse) Descriptor() ([]byte, []int) {
	return file_proto_barang_barang_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteBarangResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryResponse) Reset() {
	*x = CategoryResponse{}
	mi := &file_proto_barang_barang_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryResponse) ProtoMessage() {}

func (x *CategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_barang_barang_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryResponse.ProtoReflect.Descriptor instead.
func (*CategoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_barang_barang_proto_rawDescGZIP(), []int{8}
}

func (x *CategoryResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_barang_barang_proto protoreflect.FileDescriptor

const file_proto_barang_barang_proto_rawDesc = "" +
	"\n" +
	"\x19proto/barang/barang.proto\x12\x06barang\"I\n" +
	"\x13CreateBarangRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x02 \x01(\x05R\n" +
	"categoryId\"\x13\n" +
	"\x11GetBarangsRequest\"\"\n" +
	"\x10GetBarangRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"Y\n" +
	"\x13UpdateBarangRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x03 \x01(\x05R\n" +
	"categoryId\"%\n" +
	"\x13DeleteBarangRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"j\n" +
	"\x0eBarangResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x124\n" +
	"\bcategory\x18\x03 \x01(\v2\x18.barang.CategoryResponseR\bcategory\"F\n" +
	"\x12GetBarangsResponse\x120\n" +
	"\abarangs\x18\x01 \x03(\v2\x16.barang.BarangResponseR\abarangs\"0\n" +
	"\x14DeleteBarangResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"6\n" +
	"\x10CategoryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xe8\x02\n" +
	"\rBarangService\x12C\n" +
	"\fCreateBarang\x12\x1b.barang.CreateBarangRequest\x1a\x16.barang.BarangResponse\x12C\n" +
	"\n" +
	"GetBarangs\x12\x19.barang.GetBarangsRequest\x1a\x1a.barang.GetBarangsResponse\x12=\n" +
	"\tGetBarang\x12\x18.barang.GetBarangRequest\x1a\x16.barang.BarangResponse\x12C\n" +
	"\fUpdateBarang\x12\x1b.barang.UpdateBarangRequest\x1a\x16.barang.BarangResponse\x12I\n" +
	"\fDeleteBarang\x12\x1b.barang.DeleteBarangRequest\x1a\x1c.barang.DeleteBarangResponseB\x14Z\x12api_gateway/barangb\x06proto3"

var (
	file_proto_barang_barang_proto_rawDescOnce sync.Once
	file_proto_barang_barang_proto_rawDescData []byte
)

func file_proto_barang_barang_proto_rawDescGZIP() []byte {
	file_proto_barang_barang_proto_rawDescOnce.Do(func() {
		file_proto_barang_barang_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_barang_barang_proto_rawDesc), len(file_proto_barang_barang_proto_rawDesc)))
	})
	return file_proto_barang_barang_proto_rawDescData
}

var file_proto_barang_barang_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_barang_barang_proto_goTypes = []any{
	(*CreateBarangRequest)(nil),  // 0: barang.CreateBarangRequest
	(*GetBarangsRequest)(nil),    // 1: barang.GetBarangsRequest
	(*GetBarangRequest)(nil),     // 2: barang.GetBarangRequest
	(*UpdateBarangRequest)(nil),  // 3: barang.UpdateBarangRequest
	(*DeleteBarangRequest)(nil),  // 4: barang.DeleteBarangRequest
	(*BarangResponse)(nil),       // 5: barang.BarangResponse
	(*GetBarangsResponse)(nil),   // 6: barang.GetBarangsResponse
	(*DeleteBarangResponse)(nil), // 7: barang.DeleteBarangResponse
	(*CategoryResponse)(nil),     // 8: barang.CategoryResponse
}
var file_proto_barang_barang_proto_depIdxs = []int32{
	8, // 0: barang.BarangResponse.category:type_name -> barang.CategoryResponse
	5, // 1: barang.GetBarangsResponse.barangs:type_name -> barang.BarangResponse
	0, // 2: barang.BarangService.CreateBarang:input_type -> barang.CreateBarangRequest
	1, // 3: barang.BarangService.GetBarangs:input_type -> barang.GetBarangsRequest
	2, // 4: barang.BarangService.GetBarang:input_type -> barang.GetBarangRequest
	3, // 5: barang.BarangService.UpdateBarang:input_type -> barang.UpdateBarangRequest
	4, // 6: barang.BarangService.DeleteBarang:input_type -> barang.DeleteBarangRequest
	5, // 7: barang.BarangService.CreateBarang:output_type -> barang.BarangResponse
	6, // 8: barang.BarangService.GetBarangs:output_type -> barang.GetBarangsResponse
	5, // 9: barang.BarangService.GetBarang:output_type -> barang.BarangResponse
	5, // 10: barang.BarangService.UpdateBarang:output_type -> barang.BarangResponse
	7, // 11: barang.BarangService.DeleteBarang:output_type -> barang.DeleteBarangResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_barang_barang_proto_init() }
func file_proto_barang_barang_proto_init() {
	if File_proto_barang_barang_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_barang_barang_proto_rawDesc), len(file_proto_barang_barang_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_barang_barang_proto_goTypes,
		DependencyIndexes: file_proto_barang_barang_proto_depIdxs,
		MessageInfos:      file_proto_barang_barang_proto_msgTypes,
	}.Build()
	File_proto_barang_barang_proto = out.File
	file_proto_barang_barang_proto_goTypes = nil
	file_proto_barang_barang_proto_depIdxs = nil
}
