// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"api_gateway/config"
	"api_gateway/internal/category"
	"api_gateway/internal/server"
)

// Injectors from wire.go:

func InitializeServer() (*server.Server, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	client, err := category.NewClientCategory(configConfig)
	if err != nil {
		return nil, err
	}
	repositoryCategoryImpl := category.NewRepositoryCategory(client)
	handlerCategory := category.NewHandlerCategory(repositoryCategoryImpl)
	handlers := server.Handlers{
		Category: handlerCategory,
	}
	serverServer := server.NewServer(handlers)
	return serverServer, nil
}
